site_name: Exhausterr

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
  - Tutorials: tutorials.md
  - Differences with `returns` library: differences_returns.md
  - Manifesto: manifesto.md


theme: material